services:
  db:
    container_name: auctionit
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auctionit
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    image: redis:7
    restart: always

volumes:
  pgdata: {}

  
